### PR TITLE
reorganizing js and css + optimizing mobile css

### PR DESCRIPTION
**Pull request by goldstargloww**

### CODE REVIEW

**Review by felikatze — COMMENTED** [review]
I simply have to Trust on most of this, as you are the CSS wizard and I am not, but why'd you remove the padding from the top bar images? Did it just not work in the first place, or?

**Comment by goldstargloww** [comment]
i didn't remove them, i just removed from the head class and turned it into `#desknav img` instead :> didn't need to use a class there

**Comment by goldstargloww** [comment]
i didn't remove them, i just removed from the head class and turned it into `#desknav img` instead :> didn't need to use a class there

**Review by felikatze — APPROVED** [review]
okayo then

**Pull request merged**
