### PR TITLE
pages for boulangerie, dormont east, odile in dormont, beautiful one's house

### PR DESCRIPTION
**Pull request by raspberryspider**
i still can't spell boulangerie

### CODE REVIEW

**Comment by raspberryspider** [comment]
I FORGOT closes #154

**Comment by raspberryspider** [comment]
closes #65 too by the look of it, since gold got the change god text?

**Comment by raspberryspider** [comment]
closes #191 bc i don't know when to put things down

**Review by felikatze — APPROVED** [review]
Some notes for you!! Woo!!

- We've been wholesale moving away from bullet lists in favor of notes in basically all aspects, also including single line vars and siffrin portrait vars
- why did you make all siffrin lines an ul but only sometimes

otherwise!! i like it!! i do actually love the usage of gold's conditional thingie for the dialogue options!! very pleasantly surprised to see "occurs conditionally" with the elaboration in the dropdown: truly the best of both worlds (brevity vs specificity)

**Comment by goldstargloww** [comment]
another note, you have to put the closing keywords in the main pr description or they don't work (i'll go close those manually now ^^)

**Pull request merged**
