### PR TITLE
Reformatting Loop pages + dagger page

### PR DESCRIPTION
**Pull request by candycoatedrox**
Pages for asking Loop what to do (all acts) reformatted, plus filled out the dagger page.

### CODE REVIEW

**Review by felikatze — CHANGES_REQUESTED** [review]
First of all - everything looks pretty great! I know it's my fault that the fineries on how to do things aren't clear, so, some notes:

- Inbetween bigger headings / sections, you should use <br> AND <hr> to create more space. I find it looks less cramped this way.
- The li class option should only be used when there are multiple alternative siffrin portraits, as this allows the actual line itself to be added to the same ul as the alternate portraits are. it is not necessary during non-varied single lines and moreso breaks the flow of conversation when used there. You probably went through a lot of effort to add that, so I apologize for telling you to remove it! (You also seem to only sometimes do this?)
- on the dagger page, you seem to be missing the text for using it on allies. Great job compiling everything in a sensical order, though!

Those are some HUGE pages you reformatted very well, so be proud!! You have both my thanks and my praise.

**Comment by candycoatedrox** [comment]
Okay, I THINK I fixed everything!! Thanks for letting me know, haha.

- I kind of guessed on what you meant by "bigger sections." Sorry if it's inconsistent I guess...? But also you're totally right, it looks WAY less cramped like this
- Ahhh thank you for letting me know. Honestly I just thought it looked kinda cool and mimicked the dialogue boxes, but I'm not super invested in it, so it's fine. Actually a relatively simple fix, because I can just drag and drop the actual line into the p tag and delete the whole ul. Much less work than some of the reformatting I was doing, lol.
- Thanks for catching that!!! It totally slipped my mind while editing. Also I absolutely cannot believe that I almost let my dumb easy-to-double-click-and-replace Loop "teehee" template line make it out onto a public page. On the DAGGER PAGE. Of ALL PAGES. AAAARGH.

...I do have one tiny question about formatting for the dagger page, on the topic of the allies section. There's one line that says the name of whoever you tried to use it on, and I wasn't sure how to show that, because it feels super clunky to have a massive line break and separate line for a _literal one word change,_ but maybe that's just me. This is what I went with, but I don't really like it, and if you have a better idea absolutely tell me and I'll change it, lol.
image


It's no problem!!! Honestly, I kind of love repetitive tasks I can just zone out on for hours and still feel productive, I dunno if that sounds weird??? Plus, I love helping out fandom resources. This is like the third time I've gotten deeply into a fandom wiki reformatting project...

I'll probably do some more soon, though my RPG maker free trial runs out soon (sigh). Maybe I'll reformat the rest of Odilequest and/or start on Bonniequest. Or if you have any page requests you've been meaning to get to, I'd be happy to do that too :)

**Comment by felikatze** [comment]
> Okay, I THINK I fixed everything!! Thanks for letting me know, haha.
> 
>     * I kind of guessed on what you meant by "bigger sections." Sorry if it's inconsistent I guess...? But also you're totally right, it looks WAY less cramped like this
> 
>     * Ahhh thank you for letting me know. Honestly I just thought it looked kinda cool and mimicked the dialogue boxes, but I'm not super invested in it, so it's fine. Actually a relatively simple fix, because I can just drag and drop the actual line into the p tag and delete the whole ul. Much less work than some of the reformatting I was doing, lol.
> 
>     * Thanks for catching that!!! It totally slipped my mind while editing. Also I absolutely cannot believe that I almost let my dumb easy-to-double-click-and-replace Loop "teehee" template line make it out onto a public page. On the DAGGER PAGE. Of ALL PAGES. AAAARGH.
> 
> 
> ...I do have one tiny question about formatting for the dagger page, on the topic of the allies section. There's one line that says the name of whoever you tried to use it on, and I wasn't sure how to show that, because it feels super clunky to have a massive line break and separate line for a _literal one word change,_ but maybe that's just me. This is what I went with, but I don't really like it, and if you have a better idea absolutely tell me and I'll change it, lol. image
> 
> It's no problem!!! Honestly, I kind of love repetitive tasks I can just zone out on for hours and still feel productive, I dunno if that sounds weird??? Plus, I love helping out fandom resources. This is like the third time I've gotten deeply into a fandom wiki reformatting project...
> 
> I'll probably do some more soon, though my RPG maker free trial runs out soon (sigh). Maybe I'll reformat the rest of Odilequest and/or start on Bonniequest. Or if you have any page requests you've been meaning to get to, I'd be happy to do that too :)

**Comment by felikatze** [comment]
Wahoo. I'll check it out in-depth once I get home this evening 👍 So sadly I can't sign of just yet. Hahaaah, the wonders of employment <3

- What a bigger section is is up to gut feeling tbh. Tho at Minimum it's between every h1, and at minimum a br between every dialogue div. If it looks good, who cares about the specifics.
- In that vein, good that it wasn't too much effort to redo. Trying to break the reading flow as little is possible is good. Portrait changes do that anyways, so you can add more to those lol.
- One word changes with brackets are great, yes! It's how I've been handling dear friends like v[278] or whichever it is. Yknow, the [friends/allies/family members]. Or the act1-2 vs 3-4 [./!] I think people can figure out what it means lmao.

Hah, fandom wiki projects... I do love them. That's why i'm also fewiki editor and isatwiki admin. It's fun AND you get to gush about a thing you like.

Concerning requests: Have you checked out the projects and issues sections yet? I have a "requests" tag for issues that got requested on tumblr, and the projects (separated into isat and sasasap) serve to order requests. You can see which one's I'm working on because I put them under "In Progress" and assigned myself to them. Everything else is fair game! I've not touched them until I assigned myself to them.

Feel free to pick up whatever you want! I'm always happy to help and be helped~ I've also added some more guidelines to the wiki section, though I didn't finish the page on dialogue variations just yet. If you got anymore questions, feel free to reach out on tumblr or discord (@/felikatze). I might even be able to help with the rpgmaker issue. Winks cutely.

Thank you again!!

**Review by felikatze — APPROVED** [review]
Looking good! Yippie

**Pull request merged**
